student_performance:
  train_data_path: "artifacts/train.csv"
  test_data_path: "artifacts/test.csv"
  raw_data_path: "notebook/data/stud.csv"
  preprocessor_file_path: "artifacts/preprocessor.pkl"
  model_path: "artifacts/model.pkl"
